[project]
name = "manuelita-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.121.1",
    "langchain>=1.0.5",
    "uvicorn>=0.38.0",
]
